# Generated by Django 5.2.5 on 2025-08-06 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('restaurants', '0002_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='restaurants.restaurant'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
