# Generated by Django 5.2.5 on 2025-08-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_employee_options_employee_restaurant_and_more'),
        ('restaurants', '0002_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='restaurants.restaurant'),
        ),
    ]
